### ISSUE TITLE
nam install后报错

### ISSUE THREAD

**Issue by raighnew** [DIYgod/Resume#2]
ownloading https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-macosx.zip
Saving to /var/folders/v1/mdm82vjj7fz2skq3111pys5r0000gn/T/phantomjs/phantomjs-1.9.8-macosx.zip
Receiving...

Error making request.
Error: connect ETIMEDOUT
    at exports._errnoException (util.js:746:11)
    at TCPConnectWrap.afterConnect [as oncomplete](net.js:1010:19)

Please report this full log at https://github.com/Medium/phantomjs

npm ERR! Darwin 15.0.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE

npm ERR! phantomjs@1.9.18 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phantomjs@1.9.18 install script 'node install.js'.
npm ERR! This is most likely a problem with the phantomjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls phantomjs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/raighne/Resume/npm-debug.log

**Comment by DIYgod** [comment]
可能有些资源被墙了，挂上代理再试下呢？

**Comment by raighnew** [comment]
npm install和bower install需要一起使用吗？

发自翁浩

**Comment by DIYgod** [comment]
是的，分两次执行
