### ISSUE TITLE
自适应的问题

### ISSUE THREAD

**Issue by 777720** [DIYgod/Resume#6]
你这里针对不同设备的自适应布局尤其是字体自适应，做得非常好，请问你是怎么做到的呢？

**Comment by simon22014** [comment]
你是谁 你说的是什么？

2018-03-12 

lx22014 



发件人：雨夜浪子 <notifications@github.com>
发送时间：2018-03-12 18:23
主题：[DIYgod/Resume] 自适应的问题 (#6)
收件人："DIYgod/Resume"<Resume@noreply.github.com>
抄送："Subscribed"<subscribed@noreply.github.com>

你这里针对不同设备的自适应布局尤其是字体自适应，做得非常好，请问你是怎么做到的呢？
